repos:
  - repo: local
    hooks:
      - id: lint
        name: Linting and Formatting (isort, black, flake8)
        stages: [ commit ]
        language: system
        entry: poetry run task lint
        types: [ python ]

      - id: pytest
        name: Testing (pytest)
        stages: [ commit ]
        language: system
        entry: poetry run task test
        types: [ python ]
        pass_filenames: false